@Assecor.Api.Person_HostAddress = http://localhost:5277

### Get all persons
GET {{Assecor.Api.Person_HostAddress}}/persons
Accept: application/json

###

### Get person by ID
GET {{Assecor.Api.Person_HostAddress}}/persons/1
Accept: application/json

###

### Get persons by color
GET {{Assecor.Api.Person_HostAddress}}/persons/color/Blau
Accept: application/json

###

### Create a new person
POST {{Assecor.Api.Person_HostAddress}}/persons
Content-Type: application/json

{
  "name": "Max",
  "lastname": "Mustermann",
  "zipcode": "12345",
  "city": "Berlin",
  "color": "Blau"
}

###


